# .github/actions/my-action/action.yml
name: "Basic Setup"
description: "Clones the repository and installs dependencies platform-independently"

runs:
  using: "composite"
  steps:
    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.*

    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install winget (Windows only)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: Cyberboss/install-winget@v1

    - name: Install dependencies (Windows only)
      if: ${{ matrix.os == 'windows-latest' }}
      shell: pwsh
      run: |
        winget install --accept-source-agreements --accept-package-agreements --id DimitriVanHeesch.Doxygen
        winget install --accept-source-agreements --accept-package-agreements --id Graphviz.Graphviz

    - name: Install dependencies (Linux only)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install -y xorg-dev libboost1.83-dev \
          graphviz libharfbuzz-dev libfreetype6-dev libxcb1-dev libxcb-util-dev \
          libglx-dev libgl1-mesa-dev libxcb-xkb-dev qt6-base-dev \
          libfontconfig1-dev libfreetype6-dev libx11-dev libxext-dev \
          libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev \
          libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev \
          libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev \
          libxkbcommon-dev libxkbfile-dev libjpeg-dev libwebp-dev libtiff-dev libpng-dev
        sudo apt install apt install -y make cmake gcc g++ build-essential vim git wget curl python-is-python ninja-build

    - name: Install dependencies (MacOS only)
      if: ${{ matrix.os == 'macos-latest' }}
      shell: bash
      run: |
        brew install --formula boost doxygen graphviz harfbuzz qt@6.8.2

    - name: Install CSpell
      shell: bash
      run: npm install -g cspell
