name: CI & CD pipeline

on:
  push:

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    name: CI checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Environment basic setup
        uses: ./.github/actions/basic-setup
        with:
          cache-skia: "true"

      - name: Check spelling
        run: just check-spelling

      - name: Install tools
        # since LLVM v18 (default for Ubuntu 24) has a bug (https://github.com/llvm/llvm-project/issues/79505#issuecomment-2726487324), v19 is enforced directly
        run: |
          sudo apt update
          sudo apt install -y clang-format cppcheck
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo rm /usr/bin/clang-tidy
          sudo ln -s /usr/bin/clang-tidy-19 /usr/bin/clang-tidy

      - name: Run static code analysis with cppcheck
        run: just cppcheck

      - name: Check clang-format
        run: just check-clang-format

      - name: Run clang-tidy
        if: github.ref == 'refs/heads/main' # spare time, run this only as part of non-release workflows
        run: just clang-tidy

  cd-build-artifacts:
    needs: ci-checks
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: Build artifacts (CD)

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Environment basic setup
        uses: ./.github/actions/basic-setup
        with:
          cache-skia: "true"

      - name: Configure build
        run: just configure

      - name: Build
        run: just build-all

      - name: Run unit tests
        run: just run-tests

      - name: Upload gui_app as artifact
        id: upload-gui-app-artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui_app-${{ runner.os }}
          path: build/bin/*

      - name: Upload documentation files as artifact
        if: matrix.os == 'ubuntu-latest'
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/html/

      - name: Zip binary (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          zip -r bundle-${{ runner.os }}.zip build/bin/

      - name: Zip binary (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path build\bin\* -DestinationPath bundle-${{ runner.os }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bundle-${{ runner.os }}.zip

  cd-deploy-pages:
    needs: cd-build-artifacts
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    name: Deploy to GitHub Pages (CD)

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
