# name: CI

# on:
#   push:

# jobs:
#   build-check-code:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Environment basic setup
#         uses: ./.github/actions/basic-setup

#       - name: Check spelling
#         run: just check-spelling

#       - name: Install tools
#         run: |
#           sudo apt update
#           sudo apt install -y clang-format clang-tidy cppcheck

#       - name: Trick CMake into thinking Skia is already built
#         run: |
#           mkdir -p build/_deps/skia/out/Release
#           touch build/_deps/skia/out/Release/libskia.a

#       - name: Run static code analysis with cppcheck
#         run: cppcheck --enable=all --inconclusive --quiet --max-configs=10000 .

#       - name: Check clang-format
#         run: just check-clang-format

#       # - name: Run clang-tidy
#       #   run: just clang-tidy
